### ISSUE TITLE
Question regarding .NET Core Version Variables

### ISSUE THREAD

**Issue by MrAJP** [ninedigit/wixsharpextensions#1]
Hello, 

I've looked through the code and are very impressed with the extension methods written. The example that is used to show how to detect certain OS & .NET versions is extremely helpful, as I'm looking to bootstrap .NET 5.0 in the installer for my latest project. 

The question that I have is, you've used the variable "DOT_NET_CORE_AND_HOSTING_VERSION". Where does that come from? Is there a list of the possible variables for this? I'm not using the "hosting" version of .NET 5, rather the desktop version, and I can't find a reference to "DOT_NET_CORE_AND_HOSTING_VERSION" anywhere.

**Comment by yurislav** [comment]
Hi, 

the variable "DOT_NET_CORE_AND_HOSTING_VERSION" is just the name of the session variable.

What you are looking for is the [AddRegistrySearchAspNetCoreVersion](https://github.com/ninedigit/wixsharpextensions/blob/c626b06ae64bf890dd081db58756a7fa87c68a7d/NineDigit.WixSharpExtensions/BundleExtensions.cs#L356) extension method - this method ensures that in session variable called DOT_NET_CORE_AND_HOSTING_VERSION will be stored the .net version (e.g. "5.0").

So if you want to detect whether .NET 5 is installed, you just compare the version against your target version like this

```
var dotNetCoreHostingMinVersionInstalledCondition = WixExpression.Create(
                new WixExpression(dotNetCoreHostingVersionVariableName),
                WixComparativeExpressionOperator.Gte,
                new WixExpression(@""5.0""));
```

or if you follow the example project, all you need to do is change following line:

```
var netCoreTargetVersion = new Version(5, 0);
```

**Comment by MrAJP** [comment]
Excellent! Thanks for the explanation. That clears things up a lot. Thanks for your help!
