### ISSUE TITLE
Getting compilation error.

### ISSUE THREAD

**Issue by saiprabhur** [ninedigit/wixsharpextensions#2]
Followed all the steps provided in the sample. I have created console application using .net framework 4.5.2
Getting below error. The version detail i kept  new Version (2,0,0).
Do i missing anything ?

Unhandled Exception: System.ArgumentException: Version must not contain revision. Only first three parts (major, minor and build) are supported by Wix.
1>  Parameter name: version
1>     at NineDigit.WixSharpExtensions.ProjectExtensions.SetProjectInfo[TProject](TProject project, Guid upgradeCode, ProjectNameInfo projectName, Version version, InstallScope installScope)
1>     at NineDigit.WixSharpExtensions.ProjectExtensions.SetProjectInfo[TProject](TProject project, Guid upgradeCode, String name, String description, Version version, InstallScope installScope)
1>     at Installer.Program.Main(String[] args) in D:\SampleCode\Installer\Program.cs:line 71

**Comment by yurislav** [comment]
Hi! Can you copy snippet of your code, where the version is declared?

**Comment by saiprabhur** [comment]
Sorry for the delay. The code i have shared only version declaration and  ManagedProject.
Not shared full code. do you need please let me know.

` static void Main(string[] args)
        {
            var version = new Version(1, 0, 0); // you may want to get version from assembly dynamically with 
            Tasks.GetVersionFromFile("path-to-your-app-assembly");

            var isDebug = IsDebug();
            var netCoreTargetVersion = new Version(3, 1);
            var solutionDirectory = Directory.GetParent(Directory.GetCurrentDirectory()).FullName;
            var sourceDirectoryPath = "my/app/publish/directory"; // directory where your app is published

            var setupProjectDirectoryPath = Directory.GetCurrentDirectory();
            var assetsFolderDirectoryPath = Path.Combine(setupProjectDirectoryPath, "Assets");
            var filesFolderDirectoryPath = Path.Combine(assetsFolderDirectoryPath, "Files");
            var filesProgramMenuDirectoryPath = Path.Combine(filesFolderDirectoryPath, "ProgramMenu");
            var localizationsFolderDirectoryPath = Path.Combine(assetsFolderDirectoryPath, "Localizations");
            var outputInstallerDirectoryPath = Path.Combine(solutionDirectory, "RELEASES");
            var outputInstallerFileName = InstallerOutputFileNamePrefix + version.ToString(3);

            var msiFilePath = new ManagedProject()
                .SetProjectInfo(
                    upgradeCode: ProductUpgradeCode, // unique for this project; same value for all versions; must not be changed between versions.
                    name: ProductFullName,
                    description: ProductDescription,
                    version: version) //Error.
                .SetControlPanelInfo(`

**Comment by saiprabhur** [comment]
some more information.
https://github.com/ninedigit/wixsharpextensions/wiki/Setup-for-ASP.NET-Core-application

followed all the steps provided in the url. for that only i am getting the issue.

Created project using .Net framework 4.5.2

**Comment by saiprabhur** [comment]
resolved the issue by setting correct version.
