### ISSUE TITLE
AddWindowsServiceAndFirewallRule doesn't work with WixSharp 1.18.0

### ISSUE THREAD

**Issue by kolebynov** [ninedigit/wixsharpextensions#3]
Hi,
In WixSharp 1.18.0 `WixSharp.File.ServiceInstaller` became a property, not a field. Now project building fails with exception `System.MissingFieldException: Field not found: 'WixSharp.File.ServiceInstaller'`. Could you please bump the version of WixSharp?

**Comment by yurislav** [comment]
Yes, i'll look at it 🙂

**Comment by yurislav** [comment]
[Done](https://github.com/ninedigit/wixsharpextensions/releases/tag/v1.0.10)!
