### ISSUE TITLE
how to stop installation 32 bit OS

### ISSUE THREAD

**Issue by saiprabhur** [ninedigit/wixsharpextensions#4]
In MSI i am able to restrict to install the software in 32 bit OS,

Question : I am using bundle setup. Want to stop the installation when bundle setup exe launched. Is it possible?

**Comment by yurislav** [comment]
The restriction is not directly part of this extensions :) 
Please check the [Wix documentation](https://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/block_install_on_os.html/) and corresponding method in [Wixsharp library](https://github.com/oleg-shilo/wixsharp).

You can either wirte your own custom action, or maybe some more elegant solution is available, too.

```csharp
...

class MyCustomAction : CustomAction, ILoadAware
{
    public void OnLoad(SetupEventArgs e)
    {
       // TODO: check OS version using .NET method (Environment.Is64BitOperatingSystem) or access the "e" argument properties.
    }
}
```
