### ISSUE TITLE
After completed a custom installation of SqlExpress and rollback to install progress again

### ISSUE THREAD

**Issue by Naganathan** [ninedigit/wixsharpextensions#5]
Once completed the custom (configured the silent installation) installation SqlExpress with instances, the myproduct.exe file rollback and extract the SQLEXPR_x86_ENU.exe in "C:\ProgramData\Package Cache" folder and manual install has progress while installing the myproduct.exe. The following code we have used to configure the silent installation for sql instance.

` 
var bootstrapper = new Bundle(
                "myproduct",
                       new ExePackage(@"D:\MyProductSetup\MyProduct\Assets\SQLEXPR_x86_ENU.exe") 
                       {
                           Name = "SQLEXPR_x86_ENU.exe",
                           InstallCommand = "/qs /QUIETSIMPLE /ACTION=install /UpdateEnabled=0 /FEATURES=SQLENGINE,Tools /INSTANCENAME=ABCD /SkipRules=\"SkipInstallerRunCheck\" /SQLSVCACCOUNT=\"NT AUTHORITY\\NETWORK SERVICE\" /TCPENABLED=1 /NPENABLED=1 /IAcceptSQLServerLicenseTerms=True /SAPWD=\"******\" /SECURITYMODE=\"SQL\" /ADDCURRENTUSERASSQLADMIN /SQLSYSADMINACCOUNTS=\"Builtin\\Administrators\"",                           
                           Compressed = true
                       })
` 

is anything need to change in configuration?

**Comment by yurislav** [comment]
I'm not sure that I understood what's the issue, is it that the product.exe is not installed silently? I guess I'll need more code than you've provided.
