### ISSUE TITLE
Boot Strapper Query

### ISSUE THREAD

**Issue by saiprabhur** [ninedigit/wixsharpextensions#6]
We are packing Dotnet Core, redistributable, SQL express and our application MSI in the boot strapper.
Its work fine.
During installation i could see Dotnet and redistributable parallelly installing, Is it possible to restrict the installation in sequence ?

Sai

**Comment by yurislav** [comment]
I don't think that parallel installation is being done, all dependencies are installed in sequence AFAIK.
